=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/xsd/instance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="instance">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="activityTime" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="allowSummon" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="emptyDestroyTime" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="PvPInstance" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="showTimer" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="val" type="xs:boolean" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnPoint" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="spawnX" type="xs:integer" use="required" />
						<xs:attribute name="spawnY" type="xs:integer" use="required" />
						<xs:attribute name="spawnZ" type="xs:integer" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="doorlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="door" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="doorId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="default_status">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="open" />
												<xs:enumeration value="close" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="random_time" type="xs:integer" />
									<xs:attribute name="open_time" type="xs:integer" />
									<xs:attribute name="close_time" type="xs:integer" />
									<xs:attribute name="level" type="xs:nonNegativeInteger" />
									<xs:attribute name="open_method" type="xs:nonNegativeInteger" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="check_collision" type="xs:boolean" />
									<xs:attribute name="clanhall_id" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnlist" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="group" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="amount" type="xs:positiveInteger" />
												<xs:attribute name="heading" type="xs:integer" use="required" />
												<xs:attribute name="npcId" type="xs:positiveInteger" use="required" />
												<xs:attribute name="onKillDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="respawn" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" />
												<xs:attribute name="allowRandomWalk" type="xs:boolean" />
												<xs:attribute name="x" type="xs:integer" use="required" />
												<xs:attribute name="y" type="xs:integer" use="required" />
												<xs:attribute name="z" type="xs:integer" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:normalizedString" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:normalizedString" use="required" />
			<xs:attribute name="ejectTime" type="xs:positiveInteger" />
			<xs:attribute name="allowRandomWalk" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/instances/Ranku.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Ranku" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd">
	<activityTime val="30" />
	<allowSummon val="false" />
	<emptyDestroyTime val="300" />
	<spawnPoint spawnX="-19006" spawnY="277065" spawnZ="-13383" />
	<spawnlist>
		<group name="general">
			<spawn npcId="25542" x="-19056" y="278732" z="-15000" heading="0" respawn="0" />
		</group>
	</spawnlist>
</instance>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/instances/SecretArea.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Secret Area in the Keucereus Fortress" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd">
	<activityTime val="15" />
	<allowSummon val="false" />
	<spawnPoint spawnX="-185057" spawnY="242821" spawnZ="1576" />
	<emptyDestroyTime val="300" />
	<spawnlist>
		<group name="general">
			<spawn npcId="32567" x="-23985" y="-8965" z="-5388" heading="0" respawn="0" />
		</group>
	</spawnlist>
</instance>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/instances/Kamaloka60_70.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Kamaloka60_70" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd" >
  	<activityTime val="30"/>
	<emptyDestroyTime val="300" />
	<spawnlist>
		<group name="general">
    			<spawn npcId="22476" x="23476" y="-206310" z="-7991" heading="54483" respawn="30"/>
    			<spawn npcId="22476" x="23230" y="-205861" z="-7991" heading="480" respawn="30"/>
    			<spawn npcId="22476" x="22644" y="-205888" z="-7994" heading="9982" respawn="30"/>
    			<spawn npcId="22476" x="23078" y="-206714" z="-7991" heading="40871" respawn="30"/>
		</group>
	</spawnlist>
</instance>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/instances/SecretRitualOfThePriests.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance name="Sanctum of the Lords of Dawn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/instance.xsd" >
	<activityTime val="60" />
	<allowSummon val="false" />
	<emptyDestroyTime val="300" />
	<spawnPoint spawnX="-12532" spawnY="122329" spawnZ="-2984" />
	<doorlist>
		<door doorId="17240001" />
		<door doorId="17240003" />
		<door doorId="17240005" />
	</doorlist>
	<spawnlist>
		<group name="general">
			<!-- First room npcs -->
			<spawn npcId="32578" x="-75695" y="213537" z="-7120" heading="0" respawn="0" />
			<spawn npcId="32579" x="-75988" y="213411" z="-7120" heading="0" respawn="0" />
			<!-- Not moving guards -->
			<spawn npcId="18834" x="-74934" y="213446" z="-7216" heading="33334" respawn="0" />
			<spawn npcId="18835" x="-74951" y="211629" z="-7312" heading="16384" respawn="0" />
			<spawn npcId="27351" x="-75301" y="209980" z="-7408" heading="1722" respawn="0" />
			<spawn npcId="27351" x="-74619" y="209981" z="-7408" heading="30212" respawn="0" />
			<spawn npcId="27351" x="-74282" y="208784" z="-7504" heading="40959" respawn="0" />
			<spawn npcId="18834" x="-75654" y="208112" z="-7504" heading="2718" respawn="0" />
			<spawn npcId="18834" x="-75428" y="208115" z="-7504" heading="32768" respawn="0" />
			<spawn npcId="18834" x="-74955" y="207611" z="-7504" heading="0" respawn="0" />
			<spawn npcId="27351" x="-75454" y="206740" z="-7504" heading="34645" respawn="0" />
			<spawn npcId="27351" x="-74558" y="206625" z="-7504" heading="65102" respawn="0" />
			<spawn npcId="27351" x="-77703" y="208320" z="-7696" heading="16384" respawn="0" />
			<spawn npcId="18835" x="-77718" y="207512" z="-7696" heading="24550" respawn="0" />
			<spawn npcId="27351" x="-77703" y="207275" z="-7696" heading="49151" respawn="0" />
			<spawn npcId="18835" x="-77558" y="207138" z="-7696" heading="17906" respawn="0" />
			<spawn npcId="18835" x="-78346" y="207146" z="-7696" heading="8680" respawn="0" />
			<spawn npcId="18835" x="-78113" y="207384" z="-7696" heading="41575" respawn="0" />
			<spawn npcId="27351" x="-76962" y="207802" z="-7696" heading="35928" respawn="0" />
			<spawn npcId="18835" x="-77216" y="208297" z="-7696" heading="35486" respawn="0" />
			<spawn npcId="18835" x="-77159" y="207642" z="-7696" heading="32460" respawn="0" />
			<spawn npcId="32578" x="-78289" y="205749" z="-7880" heading="0" respawn="0" />
			<spawn npcId="32577" x="-80152" y="205740" z="-7888" heading="0" respawn="0" />
			<spawn npcId="18828" x="-79230" y="205935" z="-7896" heading="36864" respawn="0" />
			<spawn npcId="18828" x="-79362" y="206012" z="-7896" heading="49152" respawn="0" />
			<spawn npcId="18828" x="-79493" y="205930" z="-7896" heading="61440" respawn="0" />
			<spawn npcId="18828" x="-79495" y="205774" z="-7896" heading="4096" respawn="0" />
			<spawn npcId="18828" x="-79362" y="205706" z="-7896" heading="16383" respawn="0" />
			<spawn npcId="18828" x="-79229" y="205782" z="-7896" heading="28672" respawn="0" />
			<spawn npcId="27351" x="-78891" y="206272" z="-7888" heading="59013" respawn="0" />
			<spawn npcId="27351" x="-79814" y="206277" z="-7888" heading="59013" respawn="0" />
			<spawn npcId="27351" x="-79813" y="205426" z="-7888" heading="9231" respawn="0" />
			<spawn npcId="27351" x="-78926" y="205432" z="-7888" heading="23278" respawn="0" />
			<spawn npcId="27351" x="-81535" y="205503" z="-7984" heading="16384" respawn="0" />
			<spawn npcId="27351" x="-81536" y="206223" z="-7984" heading="49151" respawn="0" />
			<spawn npcId="32581" x="-81784" y="205690" z="-7960" heading="0" respawn="0" />
			<spawn npcId="32581" x="-81393" y="206152" z="-7960" heading="0" respawn="0" />
			<spawn npcId="32581" x="-81669" y="206090" z="-7960" heading="0" respawn="0" />
			<spawn npcId="32581" x="-81393" y="205565" z="-7960" heading="0" respawn="0" />
		</group>
	</spawnlist>
</instance>
