=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/xsd/phoenix_settings.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  	<xs:element name="events">
    		<xs:complexType>
			<xs:sequence>
        			<xs:element name="event">
          				<xs:complexType>
            					<xs:choice maxOccurs="unbounded" minOccurs="0">
              						<xs:element name="config" maxOccurs="unbounded" minOccurs="0">
                						<xs:complexType>
                  							<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="name" use="optional"/>
                      									<xs:attribute type="xs:string" name="value" use="optional"/>
                    								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
              						<xs:element name="restriction" maxOccurs="unbounded" minOccurs="0">
                						<xs:annotation>
                  							<xs:documentation>ENABLE/DISABLE EVENTS (temporary solution till the ingame admin panel arrives</xs:documentation>
                						</xs:annotation>
                						<xs:complexType>
                  							<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="type" use="optional"/>
                      									<xs:attribute type="xs:string" name="ids" use="optional"/>
                      									<xs:attribute type="xs:string" name="name" use="optional"/>
                      									<xs:attribute type="xs:string" name="value" use="optional"/>
                    								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
            					</xs:choice>
            					<xs:attribute type="xs:byte" name="id"/>
          				</xs:complexType>
        			</xs:element>
      			</xs:sequence>
    		</xs:complexType>
  	</xs:element>
</xs:schema>

=== Hl4p3x/L2jEternityWorld/core/dist/game/config/events/phoenix_events/Settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../data/xsd/phoenix_settings.xsd">
   	<event id="0">
      		<config name="ipCheckOnRegister" value="false" />
      		<config name="registerTime" value="600" />
      		<config name="voteTime" value="3600" />
      		<config name="voteEnabled" value="false" />
      		<config name="schedulerEnabled" value="false" />
      		<config name="firstAfterStartTime" value="60" />
      		<config name="managerNpcId" value="9999" />
      		<config name="showVotePopupAt" value="30" />
      		<config name="votePopupEnabled" value="false" />
      		<config name="debug" value="true" />
      		<config name="statTrackingEnabled" value="false" />
      		<config name="eventBufferEnabled" value="true" />
      		<config name="allowedBuffsList" value="1068,1085,1086,1087" />
      		<config name="maxBuffNum" value="2" />
      		<config name="friendlyFireEnabled" value="false" />
      		<config name="restartAllowed" value="false" />
      		<config name="showEscapeEffect" value="true" />
      		<config name="enableMiniEvents" value="false" />
      		<config name="npcBufferId" value="90001" />
      		<restriction type="item" ids="0" />
      		<restriction type="skill" ids="0" />
      		<!-- ENABLE/DISABLE EVENTS (temporary solution till the ingame admin panel arrives -->
      		<config name="eventEnabled_1" value="false" />
      		<config name="eventEnabled_2" value="false" />
      		<config name="eventEnabled_3" value="false" />
      		<config name="eventEnabled_4" value="false" />
      		<config name="eventEnabled_5" value="false" />
      		<config name="eventEnabled_6" value="false" />
      		<config name="eventEnabled_7" value="false" />
      		<config name="eventEnabled_8" value="false" />
      		<config name="eventEnabled_9" value="false" />
      		<config name="eventEnabled_10" value="false" />
   	</event>
</events>
