=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/xsd/phoenix_events.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  	<xs:element name="events">
    		<xs:complexType>
      			<xs:sequence>
        			<xs:element name="event">
          				<xs:complexType>
            					<xs:sequence>
              						<xs:element name="config" maxOccurs="unbounded" minOccurs="0">
                						<xs:complexType>
                  							<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="name" use="optional"/>
                      									<xs:attribute type="xs:string" name="value" use="optional"/>
                    								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
              						<xs:element name="color" maxOccurs="unbounded" minOccurs="0">
                                                        	<xs:complexType>
                                                                	<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="owner" use="optional"/>
                      									<xs:attribute type="xs:short" name="r" use="optional"/>
                      									<xs:attribute type="xs:short" name="g" use="optional"/>
                      									<xs:attribute type="xs:short" name="b" use="optional"/>
                    								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
              						<xs:element name="position" maxOccurs="unbounded" minOccurs="0">
                						<xs:complexType>
                  							<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="owner" use="optional"/>
                       									<xs:attribute type="xs:int" name="x" use="optional"/>
                       									<xs:attribute type="xs:int" name="y" use="optional"/>
                       									<xs:attribute type="xs:short" name="z" use="optional"/>
                       									<xs:attribute type="xs:short" name="radius" use="optional"/>
                     								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
              						<xs:element name="restriction" maxOccurs="unbounded" minOccurs="0">
                						<xs:complexType>
                  							<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="type" use="optional"/>
                      									<xs:attribute type="xs:int" name="ids" use="optional"/>
                    								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
              						<xs:element name="reward" maxOccurs="unbounded" minOccurs="0">
                						<xs:complexType>
                  							<xs:simpleContent>
                    								<xs:extension base="xs:string">
                      									<xs:attribute type="xs:string" name="owner" use="optional"/>
                      									<xs:attribute type="xs:string" name="list" use="optional"/>
                    								</xs:extension>
                  							</xs:simpleContent>
                						</xs:complexType>
              						</xs:element>
            					</xs:sequence>
            					<xs:attribute type="xs:byte" name="id"/>
          				</xs:complexType>
        			</xs:element>
      			</xs:sequence>
    		</xs:complexType>
  	</xs:element>
</xs:schema>

=== Hl4p3x/L2jEternityWorld/core/dist/game/config/events/phoenix_events/Russ.xml
<?xml version="1.0" encoding="UTF-8"?>
<events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../data/xsd/phoenix_events.xsd">
   	<event id="7">
      		<config name="shortName" value="Russ" />
      		<config name="minLvl" value="1" />
      		<config name="maxLvl" value="85" />
      		<config name="eventName" value="Russian Roulette" />
      		<config name="matchTime" value="120" />
      		<config name="allowPotions" value="false" />
      		<config name="allowUseMagic" value="false" />
      		<config name="removeBuffs" value="false" />
      		<config name="minPlayers" value="2" />
      		<config name="russianNpcId" value="9108" />
      		<config name="numberOfRussians" value="6" />
      		<config name="roundTime" value="10" />
      		<color owner="All" r="255" g="255" b="255" />
      		<position owner="All" x="-54478" y="-69506" z="-3371" radius="100" />
      		<position owner="Russian" x="-54478" y="-69506" z="-3371" radius="0" />
      		<position owner="Russian" x="-54578" y="-69506" z="-3371" radius="0" />
      		<position owner="Russian" x="-54678" y="-69506" z="-3371" radius="0" />
      		<position owner="Russian" x="-54778" y="-69506" z="-3371" radius="0" />
      		<position owner="Russian" x="-54878" y="-69506" z="-3371" radius="0" />
      		<position owner="Russian" x="-54978" y="-69506" z="-3371" radius="0" />
      		<restriction type="item" ids="0" />
      		<restriction type="skill" ids="0" />
      		<reward owner="winner" list="57,1000;1,1" />
      		<reward owner="loser" list="57,10" />
   	</event>
</events>
