=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/xsd/spawns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="spawnloc" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="amount" type="xs:positiveInteger" />
									<xs:attribute name="heading" type="xs:integer" use="required" />
									<xs:attribute name="npcId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="onKillDelay" type="xs:positiveInteger" />
									<xs:attribute name="respawnDelay" type="xs:integer" use="required" />
									<xs:attribute name="periodOfDay" type="xs:integer" use="required" />
									<xs:attribute name="locX" type="xs:integer" use="required" />
									<xs:attribute name="locY" type="xs:integer" use="required" />
									<xs:attribute name="locZ" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="spawnzone" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="amount" type="xs:positiveInteger" />
									<xs:attribute name="heading" type="xs:integer" use="required" />
									<xs:attribute name="npcId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="onKillDelay" type="xs:positiveInteger" />
									<xs:attribute name="respawnDelay" type="xs:integer" use="required" />
									<xs:attribute name="periodOfDay" type="xs:integer" use="required" />
									<xs:attribute name="locX" type="xs:integer" use="required" />
									<xs:attribute name="locY" type="xs:integer" use="required" />
									<xs:attribute name="locZ" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/spawns/21_17.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/spawns.xsd">
	<spawnloc name="fortress_of_dead_loc">
    		<spawn npcId="35638" locX="56736" locY="-26400" locZ="568" heading="49000" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="35639" locX="58128" locY="-32000" locZ="301" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="35640" locX="58024" locY="-25744" locZ="592" heading="49000" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="35641" locX="58084" locY="-29515" locZ="567" heading="49673" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="35641" locX="57827" locY="-29353" locZ="567" heading="16632" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="35642" locX="58037" locY="-26430" locZ="591" heading="49151" respawnDelay="60" periodOfDay="0" />
		<spawn npcId="35642" locX="57888" locY="-26346" locZ="588" heading="13028" respawnDelay="60" periodOfDay="0" />
		<spawn npcId="35642" locX="56943" locY="-27325" locZ="574" heading="27931" respawnDelay="60" periodOfDay="0" />
		<spawn npcId="35642" locX="57105" locY="-27182" locZ="574" heading="0" respawnDelay="60" periodOfDay="0" />
	</spawnloc> <!-- All Location NPC`s -->
</list>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/spawns/13_25.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/spawns.xsd">
	<spawnzone name="star_stone_zone_15">
    		<spawn npcId="18690" locX="-223331" locY="233909" locZ="4166" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18690" locX="-224189" locY="233518" locZ="4569" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18690" locX="-224618" locY="237037" locZ="4867" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18690" locX="-226334" locY="232736" locZ="5046" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18690" locX="-221615" locY="233518" locZ="4360" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18690" locX="-221615" locY="232736" locZ="4569" heading="0" respawnDelay="60" periodOfDay="0" />
	</spawnzone> <!-- Green Star Stone -->
	<spawnzone name="star_stone_zone_16">
    		<spawn npcId="18691" locX="-220757" locY="233127" locZ="4864" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18691" locX="-222044" locY="233127" locZ="4246" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18691" locX="-222473" locY="237037" locZ="5276" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18691" locX="-224189" locY="233909" locZ="4879" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18691" locX="-226763" locY="233909" locZ="5393" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18691" locX="-226334" locY="234300" locZ="5411" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18691" locX="-227192" locY="233909" locZ="5229" heading="0" respawnDelay="60" periodOfDay="0" />
	</spawnzone> <!-- Green Star Stone -->
	<spawnzone name="star_stone_zone_17">
    		<spawn npcId="18692" locX="-223760" locY="237037" locZ="4733" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18692" locX="-225476" locY="238601" locZ="4107" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18692" locX="-224618" locY="232345" locZ="5341" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18692" locX="-221186" locY="232345" locZ="5436" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18692" locX="-221186" locY="235082" locZ="3960" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="18692" locX="-222473" locY="235473" locZ="4018" heading="0" respawnDelay="60" periodOfDay="0" />
	</spawnzone> <!-- Green Star Stone -->
	<spawnloc name="gracia_npc_zone_03">
    		<spawn npcId="32518" locX="-204849" locY="242148" locZ="1781" heading="0" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="32519" locX="-223211" locY="247803" locZ="1781" heading="0" respawnDelay="60" periodOfDay="0" />
	</spawnloc> <!-- Vortex Gate -->
</list>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/spawns/20_13.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/spawns.xsd">
	<spawnzone name="orc_village_zone_49">
    		<spawn npcId="20333" locX="8783" locY="-137084" locZ="-968" heading="55865" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20333" locX="8145" locY="-137155" locZ="-856" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20333" locX="7380" locY="-135325" locZ="-784" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20333" locX="5720" locY="-132618" locZ="-2880" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20333" locX="2486" locY="-132048" locZ="-3232" heading="48875" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20333" locX="2948" locY="-132618" locZ="-3136" heading="31402" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20333" locX="2024" locY="-132390" locZ="-3224" heading="0" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Greystone Golem -->
	<spawnzone name="orc_village_zone_50">
    		<spawn npcId="20364" locX="16164" locY="-135909" locZ="-1056" heading="16257" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="14384" locY="-136226" locZ="-1432" heading="48961" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="17092" locY="-135969" locZ="-960" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="10260" locY="-133449" locZ="-1592" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="10998" locY="-134384" locZ="-1424" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="6857" locY="-137770" locZ="-680" heading="32057" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="6870" locY="-137155" locZ="-648" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="7125" locY="-136240" locZ="-704" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="8030" locY="-132276" locZ="-2760" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="10998" locY="-132327" locZ="-1704" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="5258" locY="-131478" locZ="-3160" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="1100" locY="-131706" locZ="-3304" heading="33679" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20364" locX="1562" locY="-131934" locZ="-3312" heading="0" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Maraku Werewolf Chieftain -->
	<spawnzone name="orc_village_zone_51">
    		<spawn npcId="20428" locX="10752" locY="-134571" locZ="-1432" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="10014" locY="-134197" locZ="-1424" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="9034" locY="-135408" locZ="-1032" heading="39649" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="8145" locY="-136606" locZ="-864" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="7380" locY="-135508" locZ="-776" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="2486" locY="-133302" locZ="-3168" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="638" locY="-133530" locZ="-3208" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="10260" locY="-132514" locZ="-1752" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="8954" locY="-131820" locZ="-2456" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20428" locX="3410" locY="-131592" locZ="-3256" heading="0" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Evil Eye Patroller -->
	<spawnzone name="orc_village_zone_52">
    		<spawn npcId="20474" locX="12720" locY="-131766" locZ="-1416" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20474" locX="10998" locY="-134758" locZ="-1352" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20474" locX="14013" locY="-140250" locZ="-1872" heading="27423" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20474" locX="14465" locY="-139628" locZ="-1576" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20474" locX="10363" locY="-140515" locZ="-1872" heading="58798" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20474" locX="10926" locY="-142376" locZ="-1872" heading="52885" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20474" locX="11982" locY="-131953" locZ="-1512" heading="0" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Kasha Spider -->
	<spawnzone name="orc_village_zone_53">
    		<spawn npcId="20476" locX="21274" locY="-131908" locZ="-1584" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="19650" locY="-131568" locZ="-1712" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="16532" locY="-136140" locZ="-960" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="16812" locY="-135285" locZ="-1080" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="15578" locY="-135531" locZ="-1208" heading="38014" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="10462" locY="-139935" locZ="-1872" heading="21278" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="11139" locY="-140855" locZ="-1800" heading="2180" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="10561" locY="-140878" locZ="-1840" heading="16514" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20476" locX="10867" locY="-141357" locZ="-1872" heading="0" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Kasha Fang Spider -->
	<spawnzone name="orc_village_zone_54">
    		<spawn npcId="20478" locX="22289" locY="-131704" locZ="-1616" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20478" locX="18838" locY="-131568" locZ="-1712" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20478" locX="13045" locY="-138937" locZ="-1872" heading="45088" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20478" locX="11892" locY="-140626" locZ="-1872" heading="45616" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20478" locX="10874" locY="-142074" locZ="-1872" heading="63645" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Kasha Blade Spider -->
	<spawnzone name="orc_village_zone_55">
    		<spawn npcId="20479" locX="21477" locY="-131840" locZ="-1616" heading="59372" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20479" locX="21274" locY="-132180" locZ="-1576" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20479" locX="21071" locY="-132180" locZ="-1632" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20479" locX="15972" locY="-134943" locZ="-1272" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20479" locX="15132" locY="-136311" locZ="-1208" heading="0" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20479" locX="14770" locY="-136152" locZ="-1400" heading="48320" respawnDelay="21" periodOfDay="0" />
    		<spawn npcId="20479" locX="12015" locY="-140472" locZ="-1872" heading="16146" respawnDelay="21" periodOfDay="0" />
	</spawnzone> <!-- Kasha Bear -->
	<spawnloc name="orc_village_loc_05">
    		<spawn npcId="30590" locX="12432" locY="-141808" locZ="-1877" heading="16384" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="31036" locX="12155" locY="-134292" locZ="-1184" heading="58775" respawnDelay="60" periodOfDay="0" />
	</spawnloc>
</list>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/spawns/21_20.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/spawns.xsd">
	<spawnzone name="elven_village_zone_47">
    		<spawn npcId="20013" locX="57661" locY="77516" locZ="-3552" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="56437" locY="78587" locZ="-3560" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="57814" locY="78587" locZ="-3576" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="56425" locY="83499" locZ="-3560" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="57140" locY="83007" locZ="-3552" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="56035" locY="85467" locZ="-3576" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="55853" locY="84606" locZ="-3552" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20013" locX="56237" locY="87267" locZ="-3584" heading="0" respawnDelay="15" periodOfDay="0" />
	</spawnzone> <!-- Dryad -->
	<spawnzone name="elven_village_zone_48">
    		<spawn npcId="20019" locX="56743" locY="79505" locZ="-3552" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20019" locX="58273" locY="79811" locZ="-3576" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20019" locX="57283" locY="83868" locZ="-3552" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20019" locX="57569" locY="83499" locZ="-3544" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20019" locX="56338" locY="86517" locZ="-3624" heading="25348" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20019" locX="55833" locY="87267" locZ="-3576" heading="0" respawnDelay="15" periodOfDay="0" />
	</spawnzone> <!-- Dryad Elder -->
	<spawnzone name="elven_village_zone_49">
    		<spawn npcId="20460" locX="56854" locY="83745" locZ="-3552" heading="24214" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20460" locX="55732" locY="86667" locZ="-3592" heading="0" respawnDelay="15" periodOfDay="0" />
	</spawnzone> <!-- Crimson Spider -->
	<spawnzone name="elven_village_zone_50">
    		<spawn npcId="20471" locX="54612" locY="67264" locZ="-3544" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20471" locX="56132" locY="66072" locZ="-3464" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20471" locX="54225" locY="70490" locZ="-3480" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20471" locX="54588" locY="71370" locZ="-3416" heading="0" respawnDelay="15" periodOfDay="0" />
	</spawnzone> <!-- Kaboo Orc Fighter -->
	<spawnzone name="elven_village_zone_51">
    		<spawn npcId="20472" locX="54612" locY="66966" locZ="-3536" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20472" locX="54156" locY="67711" locZ="-3592" heading="1123" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20472" locX="54951" locY="71150" locZ="-3448" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20472" locX="56437" locY="79046" locZ="-3536" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20472" locX="57814" locY="78281" locZ="-3576" heading="0" respawnDelay="15" periodOfDay="0" />
	</spawnzone> <!-- Kaboo Orc Fighter Leader -->
	<spawnzone name="elven_village_zone_52">
    		<spawn npcId="20473" locX="54612" locY="67264" locZ="-3544" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20473" locX="55372" locY="67860" locZ="-3576" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20473" locX="55072" locY="70490" locZ="-3560" heading="0" respawnDelay="15" periodOfDay="0" />
    		<spawn npcId="20473" locX="54126" locY="71556" locZ="-3368" heading="55369" respawnDelay="15" periodOfDay="0" />
	</spawnzone> <!-- Kaboo Orc Fighter Lieutenant -->
	<spawnzone name="oren28_2219_01">
    		<spawn npcId="20584" locX="65042" locY="72974" locZ="-3723" heading="47831" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20585" locX="65494" locY="69406" locZ="-3723" heading="39535" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20586" locX="65324" locY="70222" locZ="-3713" heading="37652" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20586" locX="65002" locY="71201" locZ="-3691" heading="35518" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20586" locX="65215" locY="71997" locZ="-3717" heading="28802" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20587" locX="64788" locY="66771" locZ="-3688" heading="7792" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20767" locX="64879" locY="65564" locZ="-3681" heading="32730" respawnDelay="40" periodOfDay="0" />
    		<spawn npcId="20767" locX="64248" locY="70585" locZ="-3522" heading="36253" respawnDelay="40" periodOfDay="0" />
	</spawnzone> <!-- Timak Orcs -->
	<spawnzone name="elven_village_zone_53">
    		<spawn npcId="27064" locX="40494" locY="68888" locZ="-3548" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27065" locX="36148" locY="81950" locZ="-3592" heading="47071" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27066" locX="36273" locY="81761" locZ="-3616" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27066" locX="36368" locY="81877" locZ="-3616" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27067" locX="45499" locY="91692" locZ="-3552" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27068" locX="58086" locY="77350" locZ="-3536" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27069" locX="58113" locY="77163" locZ="-3528" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27069" locX="57974" locY="77296" locZ="-3536" heading="0" respawnDelay="180" periodOfDay="0" />
	</spawnzone>
	<spawnzone name="elven_village_zone_54">
    		<spawn npcId="27077" locX="56214" locY="90020" locZ="-3616" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27077" locX="49061" locY="92034" locZ="-3664" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27077" locX="47496" locY="89513" locZ="-3488" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27077" locX="42840" locY="92980" locZ="-3672" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27077" locX="38148" locY="91274" locZ="-3400" heading="0" respawnDelay="180" periodOfDay="0" />
    		<spawn npcId="27077" locX="35345" locY="89791" locZ="-3440" heading="0" respawnDelay="180" periodOfDay="0" />
	</spawnzone> <!-- Unicorn Of Eva -->
	<spawnloc name="elven_village_territory_loc">
    		<spawn npcId="30371" locX="51210" locY="82474" locZ="-3283" heading="6000" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="30749" locX="63906" locY="74711" locZ="-3667" heading="57344" respawnDelay="60" periodOfDay="0" />
    		<spawn npcId="31033" locX="35872" locY="78095" locZ="-3600" heading="0" respawnDelay="60" periodOfDay="0" />
	</spawnloc>  <!-- All Territory NPC`s -->
</list>
