=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/xsd/dtd/knoriks_route.dtd
<!ELEMENT list (Knoriks)* >
<!ELEMENT Knoriks (pathRoute)* >
<!ELEMENT pathRoute EMPTY >

<!ATTLIST Knoriks
	id CDATA #REQUIRED
>

<!ATTLIST pathRoute
	position CDATA #REQUIRED
	locX CDATA #REQUIRED
	locY CDATA #REQUIRED
	locZ CDATA #REQUIRED
>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/spawnZones/knoriks_route.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../xsd/dtd/knoriks_route.dtd">
<list>
  	<Knoriks id="1">
		<pathRoute position="0" locX="141848" locY="121592" locZ="-3912" />
		<pathRoute position="1" locX="141848" locY="121592" locZ="-3912" />
		<pathRoute position="2" locX="140440" locY="120264" locZ="-3912" />
		<pathRoute position="3" locX="140664" locY="118328" locZ="-3912" />
		<pathRoute position="4" locX="142104" locY="117400" locZ="-3912" />
		<pathRoute position="5" locX="142968" locY="117816" locZ="-3912" />
		<pathRoute position="6" locX="142648" locY="119672" locZ="-3912" />
		<pathRoute position="7" locX="143864" locY="121016" locZ="-3896" />
		<pathRoute position="8" locX="144504" locY="119320" locZ="-3896" />
		<pathRoute position="9" locX="145448" locY="117624" locZ="-3912" />
		<pathRoute position="10" locX="146824" locY="118328" locZ="-3984" />
		<pathRoute position="11" locX="147080" locY="119320" locZ="-4288" />
		<pathRoute position="12" locX="147432" locY="121224" locZ="-4768" />
		<pathRoute position="13" locX="149640" locY="119480" locZ="-4864" />
		<pathRoute position="14" locX="150616" locY="118312" locZ="-4936" />
		<pathRoute position="15" locX="152936" locY="116664" locZ="-5256" />
		<pathRoute position="16" locX="153208" locY="115224" locZ="-5256" />
		<pathRoute position="17" locX="151656" locY="115080" locZ="-5472" />
		<pathRoute position="18" locX="148824" locY="114888" locZ="-5472" />
		<pathRoute position="19" locX="151128" locY="114520" locZ="-5464" />
		<pathRoute position="20" locX="153320" locY="112728" locZ="-5520" />
		<pathRoute position="21" locX="153096" locY="111800" locZ="-5520" />
		<pathRoute position="22" locX="150504" locY="111256" locZ="-5520" />
		<pathRoute position="23" locX="149512" locY="111080" locZ="-5488" />
		<pathRoute position="24" locX="149304" locY="109672" locZ="-5216" />
		<pathRoute position="25" locX="151864" locY="109368" locZ="-5152" />
		<pathRoute position="26" locX="153320" locY="109032" locZ="-5152" />
		<pathRoute position="27" locX="153048" locY="108040" locZ="-5152" />
		<pathRoute position="28" locX="150888" locY="107320" locZ="-4800" />
		<pathRoute position="29" locX="149320" locY="108456" locZ="-4424" />
		<pathRoute position="30" locX="147704" locY="107256" locZ="-4048" />
		<pathRoute position="31" locX="146648" locY="108376" locZ="-3664" />
		<pathRoute position="32" locX="146408" locY="110200" locZ="-3472" />
		<pathRoute position="33" locX="146568" locY="111784" locZ="-3552" />
		<pathRoute position="34" locX="147896" locY="112584" locZ="-3720" />
		<pathRoute position="35" locX="148904" locY="113208" locZ="-3720" />
		<pathRoute position="36" locX="149256" locY="114824" locZ="-3720" />
		<pathRoute position="37" locX="149688" locY="116344" locZ="-3704" />
		<pathRoute position="38" locX="150680" locY="117880" locZ="-3688" />
		<pathRoute position="39" locX="152056" locY="118968" locZ="-3808" />
		<pathRoute position="40" locX="152696" locY="120040" locZ="-3808" />
		<pathRoute position="41" locX="151928" locY="121352" locZ="-3808" />
		<pathRoute position="42" locX="152856" locY="121752" locZ="-3808" />
		<pathRoute position="43" locX="154440" locY="121208" locZ="-3808" />
		<pathRoute position="44" locX="152856" locY="121752" locZ="-3808" />
		<pathRoute position="45" locX="151928" locY="121352" locZ="-3808" />
		<pathRoute position="46" locX="152696" locY="120040" locZ="-3808" />
		<pathRoute position="47" locX="152056" locY="118968" locZ="-3808" />
		<pathRoute position="48" locX="150680" locY="117880" locZ="-3688" />
		<pathRoute position="49" locX="149688" locY="116344" locZ="-3704" />
		<pathRoute position="50" locX="149256" locY="114824" locZ="-3720" />
		<pathRoute position="51" locX="148904" locY="113208" locZ="-3720" />
		<pathRoute position="52" locX="147896" locY="112584" locZ="-3720" />
		<pathRoute position="53" locX="146568" locY="111784" locZ="-3552" />
		<pathRoute position="54" locX="146408" locY="110200" locZ="-3472" />
		<pathRoute position="55" locX="146648" locY="108376" locZ="-3664" />
		<pathRoute position="56" locX="147704" locY="107256" locZ="-4048" />
		<pathRoute position="57" locX="149320" locY="108456" locZ="-4424" />
		<pathRoute position="58" locX="150888" locY="107320" locZ="-4800" />
		<pathRoute position="59" locX="153048" locY="108040" locZ="-5152" />
		<pathRoute position="60" locX="153320" locY="109032" locZ="-5152" />
		<pathRoute position="61" locX="151864" locY="109368" locZ="-5152" />
		<pathRoute position="62" locX="149304" locY="109672" locZ="-5216" />
		<pathRoute position="63" locX="149512" locY="111080" locZ="-5488" />
		<pathRoute position="64" locX="150504" locY="111256" locZ="-5520" />
		<pathRoute position="65" locX="153096" locY="111800" locZ="-5520" />
		<pathRoute position="66" locX="153320" locY="112728" locZ="-5520" />
		<pathRoute position="67" locX="151128" locY="114520" locZ="-5464" />
		<pathRoute position="68" locX="148824" locY="114888" locZ="-5472" />
		<pathRoute position="69" locX="151656" locY="115080" locZ="-5472" />
		<pathRoute position="70" locX="153208" locY="115224" locZ="-5256" />
		<pathRoute position="71" locX="152936" locY="116664" locZ="-5256" />
		<pathRoute position="72" locX="150616" locY="118312" locZ="-4936" />
		<pathRoute position="73" locX="149640" locY="119480" locZ="-4864" />
		<pathRoute position="74" locX="147432" locY="121224" locZ="-4768" />
		<pathRoute position="75" locX="147080" locY="119320" locZ="-4288" />
		<pathRoute position="76" locX="146824" locY="118328" locZ="-3984" />
		<pathRoute position="77" locX="145448" locY="117624" locZ="-3912" />
		<pathRoute position="78" locX="144504" locY="119320" locZ="-3896" />
		<pathRoute position="79" locX="143864" locY="121016" locZ="-3896" />
		<pathRoute position="80" locX="142648" locY="119672" locZ="-3912" />
		<pathRoute position="81" locX="142968" locY="117816" locZ="-3912" />
		<pathRoute position="82" locX="142104" locY="117400" locZ="-3912" />
		<pathRoute position="83" locX="140664" locY="118328" locZ="-3912" />
		<pathRoute position="84" locX="140440" locY="120264" locZ="-3912" />
  	</Knoriks>
  	<Knoriks id="2">
		<pathRoute position="0" locX="141147" locY="114516" locZ="-3725" />
		<pathRoute position="1" locX="142010" locY="114465" locZ="-3725" />
		<pathRoute position="2" locX="142559" locY="113629" locZ="-3725" />
		<pathRoute position="3" locX="143721" locY="114826" locZ="-3725" />
		<pathRoute position="4" locX="144885" locY="114590" locZ="-3725" />
		<pathRoute position="5" locX="145400" locY="115715" locZ="-3725" />
		<pathRoute position="5" locX="144885" locY="114590" locZ="-3725" />
		<pathRoute position="6" locX="146782" locY="116449" locZ="-3718" />
		<pathRoute position="7" locX="148853" locY="115766" locZ="-3716" />
		<pathRoute position="8" locX="149252" locY="113482" locZ="-3725" />
		<pathRoute position="9" locX="148207" locY="113862" locZ="-3725" />
		<pathRoute position="10" locX="148673" locY="112563" locZ="-3725" />
		<pathRoute position="11" locX="147310" locY="112549" locZ="-3725" />
		<pathRoute position="12" locX="146492" locY="111892" locZ="-3572" />
		<pathRoute position="13" locX="146375" locY="111287" locZ="-3573" />
		<pathRoute position="14" locX="146375" locY="111287" locZ="-3573" />
		<pathRoute position="15" locX="146492" locY="111892" locZ="-3572" />
		<pathRoute position="16" locX="147310" locY="112549" locZ="-3725" />
		<pathRoute position="17" locX="148673" locY="112563" locZ="-3725" />
		<pathRoute position="18" locX="148207" locY="113862" locZ="-3725" />
		<pathRoute position="19" locX="149252" locY="113482" locZ="-3725" />
		<pathRoute position="20" locX="148853" locY="115766" locZ="-3716" />
		<pathRoute position="21" locX="146782" locY="116449" locZ="-3718" />
		<pathRoute position="22" locX="145400" locY="115715" locZ="-3725" />
		<pathRoute position="23" locX="144885" locY="114590" locZ="-3725" />
		<pathRoute position="24" locX="143721" locY="114826" locZ="-3725" />
		<pathRoute position="25" locX="142559" locY="113629" locZ="-3725" />
		<pathRoute position="26" locX="142010" locY="114465" locZ="-3725" />
  	</Knoriks>
  	<Knoriks id="3">
		<pathRoute position="0" locX="148353" locY="117599" locZ="-3716" />
		<pathRoute position="1" locX="147652" locY="117455" locZ="-3701" />
		<pathRoute position="2" locX="146740" locY="116406" locZ="-3725" />
		<pathRoute position="3" locX="145047" locY="115023" locZ="-3725" />
		<pathRoute position="4" locX="143617" locY="114489" locZ="-3725" />
		<pathRoute position="5" locX="142718" locY="113581" locZ="-3725" />
		<pathRoute position="6" locX="141993" locY="114445" locZ="-3725" />
		<pathRoute position="7" locX="141231" locY="114456" locZ="-3716" />
		<pathRoute position="8" locX="141993" locY="114445" locZ="-3725" />
		<pathRoute position="9" locX="142718" locY="113581" locZ="-3725" />
		<pathRoute position="10" locX="143617" locY="114489" locZ="-3725" />
		<pathRoute position="11" locX="145047" locY="115023" locZ="-3725" />
		<pathRoute position="12" locX="146740" locY="116406" locZ="-3725" />
		<pathRoute position="13" locX="147652" locY="117455" locZ="-3701" />
  	</Knoriks>
  	<Knoriks id="4">
		<pathRoute position="0" locX="147212" locY="112375" locZ="-3725" />
		<pathRoute position="1" locX="145307" locY="113010" locZ="-3725" />
		<pathRoute position="2" locX="144901" locY="115402" locZ="-3725" />
		<pathRoute position="3" locX="146054" locY="116203" locZ="-3725" />
		<pathRoute position="4" locX="148146" locY="115983" locZ="-3725" />
		<pathRoute position="5" locX="149178" locY="115300" locZ="-3725" />
		<pathRoute position="6" locX="149145" locY="113373" locZ="-3728" />
		<pathRoute position="7" locX="148310" locY="112051" locZ="-3725" />
		<pathRoute position="8" locX="146572" locY="116231" locZ="-3725" />
		<pathRoute position="9" locX="148625" locY="115924" locZ="-3725" />
		<pathRoute position="10" locX="149271" locY="113936" locZ="-3725" />
