=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/xsd/dtd/selmahum_chefs.dtd
<!ELEMENT list (chef)* >
<!ELEMENT chef (pathPoint)* >
<!ELEMENT pathPoint EMPTY >

<!ATTLIST chef
	id CDATA #REQUIRED
>

<!ATTLIST pathPoint
	order CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
>

=== Hl4p3x/L2jEternityWorld/datapack/dist/game/data/spawnZones/selmahum_chefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "../xsd/dtd/selmahum_chefs.dtd">
<list>
  	<chef id="1">
    		<pathPoint order="0" x="85863" y="53219" z="-3616" />
    		<pathPoint order="1" x="85771" y="54272" z="-3656" />
    		<pathPoint order="2" x="86672" y="54027" z="-3704" />
    		<pathPoint order="3" x="87272" y="54514" z="-3664" />
    		<pathPoint order="4" x="89003" y="53959" z="-3712" />
    		<pathPoint order="5" x="89902" y="54124" z="-3752" />
    		<pathPoint order="6" x="90611" y="54200" z="-3776" />
    		<pathPoint order="7" x="91299" y="54961" z="-3760" />
  	</chef>
  	<chef id="2">
    		<pathPoint order="0" x="91232" y="57706" z="-3712" />
    		<pathPoint order="1" x="91845" y="56712" z="-3552" />
    		<pathPoint order="2" x="91694" y="54914" z="-3752" />
    		<pathPoint order="3" x="92724" y="54581" z="-3680" />
    		<pathPoint order="4" x="93972" y="54369" z="-3616" />
    		<pathPoint order="5" x="94357" y="54740" z="-3576" />
    		<pathPoint order="6" x="93962" y="55668" z="-3448" />
  	</chef>
  	<chef id="3">
    		<pathPoint order="0" x="91124" y="57845" z="-3744" />
    		<pathPoint order="1" x="90877" y="58092" z="-3784" />
    		<pathPoint order="2" x="90758" y="58538" z="-3784" />
    		<pathPoint order="3" x="90034" y="58630" z="-3696" />
    		<pathPoint order="4" x="88966" y="58476" z="-3680" />
    		<pathPoint order="5" x="87398" y="59174" z="-3568" />
    		<pathPoint order="6" x="87048" y="59519" z="-3560" />
    		<pathPoint order="7" x="86662" y="60462" z="-3512" />
    		<pathPoint order="8" x="87086" y="60832" z="-3560" />
    		<pathPoint order="9" x="87341" y="61052" z="-3608" />
    		<pathPoint order="10" x="88411" y="60258" z="-3584" />
  	</chef>
  	<chef id="4">
    		<pathPoint order="0" x="93445" y="59909" z="-3272" />
    		<pathPoint order="1" x="91052" y="59914" z="-3624" />
    		<pathPoint order="2" x="90131" y="60660" z="-3624" />
    		<pathPoint order="3" x="89373" y="60243" z="-3664" />
    		<pathPoint order="4" x="88429" y="60713" z="-3632" />
    		<pathPoint order="5" x="87994" y="60383" z="-3568" />
    		<pathPoint order="6" x="87592" y="59308" z="-3552" />
  	</chef>
  	<chef id="5">
    		<pathPoint order="0" x="93009" y="60859" z="-3288" />
    		<pathPoint order="1" x="93136" y="61642" z="-3240" />
    		<pathPoint order="2" x="93409" y="62175" z="-3264" />
    		<pathPoint order="3" x="93485" y="62902" z="-3288" />
    		<pathPoint order="4" x="93233" y="63938" z="-3344" />
    		<pathPoint order="5" x="92050" y="64619" z="-3528" />
    		<pathPoint order="6" x="91631" y="65084" z="-3576" />
    		<pathPoint order="7" x="91473" y="65182" z="-3608" />
    		<pathPoint order="8" x="88101" y="65221" z="-3720" />
    		<pathPoint order="9" x="87891" y="64731" z="-3720" />
    		<pathPoint order="10" x="87301" y="64469" z="-3696" />
    		<pathPoint order="11" x="86628" y="64917" z="-3632" />
  	</chef>
  	<chef id="6">
    		<pathPoint order="0" x="83423" y="65778" z="-3008" />
    		<pathPoint order="1" x="83645" y="66092" z="-3040" />
    		<pathPoint order="2" x="84046" y="65814" z="-3112" />
    		<pathPoint order="3" x="84694" y="65775" z="-3192" />
    		<pathPoint order="4" x="85297" y="65784" z="-3232" />
    		<pathPoint order="5" x="85797" y="66095" z="-3312" />
    		<pathPoint order="6" x="86699" y="65770" z="-3576" />
    		<pathPoint order="7" x="88090" y="65715" z="-3720" />
  	</chef>
  	<chef id="7">
    		<pathPoint order="0" x="90318" y="67367" z="-3696" />
    		<pathPoint order="1" x="91119" y="67615" z="-3608" />
    		<pathPoint order="2" x="90281" y="67327" z="-3704" />
    		<pathPoint order="3" x="90750" y="67108" z="-3664" />
    		<pathPoint order="4" x="91665" y="67330" z="-3648" />
    		<pathPoint order="5" x="91882" y="67895" z="-3592" />
    		<pathPoint order="6" x="91395" y="68339" z="-3544" />
    		<pathPoint order="7" x="90854" y="68223" z="-3576" />
    		<pathPoint order="8" x="89982" y="68363" z="-3656" />
    		<pathPoint order="9" x="89654" y="67430" z="-3424" />
    		<pathPoint order="10" x="88953" y="69697" z="-3344" />
    		<pathPoint order="11" x="88312" y="68948" z="-3176" />
    		<pathPoint order="12" x="87848" y="68772" z="-3128" />
    		<pathPoint order="13" x="87404" y="69395" z="-3064" />
    		<pathPoint order="14" x="86057" y="69467" z="-3064" />
    		<pathPoint order="15" x="85736" y="69088" z="-3064" />
    		<pathPoint order="16" x="85747" y="67846" z="-3064" />
    		<pathPoint order="17" x="86047" y="67581" z="-3064" />
    		<pathPoint order="18" x="86568" y="67763" z="-3064" />
    		<pathPoint order="19" x="87054" y="67669" z="-3080" />
  	</chef>
  	<chef id="8">
    		<pathPoint order="0" x="82834" y="69551" z="-3128" />
    		<pathPoint order="1" x="82496" y="70003" z="-3248" />
    		<pathPoint order="2" x="81701" y="69853" z="-3344" />
    		<pathPoint order="3" x="81132" y="69397" z="-3400" />
    		<pathPoint order="4" x="80754" y="68772" z="-3448" />
    		<pathPoint order="5" x="81043" y="65905" z="-3384" />
  	</chef>
  	<chef id="9">
    		<pathPoint order="0" x="78436" y="63486" z="-3640" />
    		<pathPoint order="1" x="78944" y="63730" z="-3608" />
    		<pathPoint order="2" x="79257" y="64129" z="-3496" />
    		<pathPoint order="3" x="79114" y="65248" z="-3304" />
    		<pathPoint order="4" x="81568" y="64969" z="-3296" />
    		<pathPoint order="5" x="81680" y="63583" z="-3576" />
    		<pathPoint order="6" x="82343" y="63795" z="-3584" />
    		<pathPoint order="7" x="83279" y="63970" z="-3568" />
    		<pathPoint order="8" x="83847" y="63303" z="-3584" />
    		<pathPoint order="9" x="85249" y="63492" z="-3688" />
    		<pathPoint order="10" x="85917" y="64558" z="-3640" />
  	</chef>
  	<chef id="10">
    		<pathPoint order="0" x="84030" y="62544" z="-3456" />
    		<pathPoint order="1" x="84441" y="63019" z="-3576" />
    		<pathPoint order="2" x="85724" y="62977" z="-3624" />
    		<pathPoint order="3" x="86310" y="62590" z="-3656" />
    		<pathPoint order="4" x="86526" y="61665" z="-3616" />
    		<pathPoint order="5" x="87281" y="61481" z="-3648" />
  	</chef>
  	<chef id="11">
    		<pathPoint order="0" x="77801" y="68818" z="-3112" />
    		<pathPoint order="1" x="77894" y="69518" z="-3096" />
    		<pathPoint order="2" x="78510" y="69888" z="-3152" />
    		<pathPoint order="3" x="79208" y="69424" z="-3304" />
    		<pathPoint order="4" x="79521" y="69026" z="-3328" />
    		<pathPoint order="5" x="80065" y="69348" z="-3384" />
    		<pathPoint order="6" x="80569" y="68766" z="-3440" />
    		<pathPoint order="7" x="80548" y="68729" z="-3448" />
    		<pathPoint order="8" x="80962" y="65966" z="-3384" />
  	</chef>
</list>
